### PR TITLE
Add PathFinder for Dijkstra and A-Star algorithms

### PR DESCRIPTION
**Pull request by msteiger**
This PR adds path-finding support. It ..
* supports Dijkstra's algorithm, A-Star (A*) and Best-First Search
* clean implementation (at least I tried my best)
* documented
* very flexible (vertex is a generic parameter, edge is a simple 3 method interface)
* non-viral OSS license (Apache 2)
* can be used with modern Java8 features
* comes with unit tests

Kudos go to AmitP for the very well written [Introduction to A*](http://theory.stanford.edu/~amitp/GameProgramming/AStarComparison.html).
A demonstration video of Dijkstra and A* can be watched here: https://youtu.be/Te7aqQCPSX0

### CODE REVIEW

**Comment by Josharias** [comment]
Sweet,  Ill see how this can be used in the entity network stuff I have been working on lately.  My implementation does not do anything with the cost of a path like yours does.

**Comment by Cervator** [comment]
Very cool :-)

At the risk of sounding pedantic: does this go in a math lib? It very well may, but it makes me think about the AI libs that exist out there (which probably include/use a lot of math too), not to mention the Pathfinding module we have. What goes where?

In any case it is awesome to see movement on this topic, no matter where it goes :-)

**Comment by immortius** [comment]
I agree with Cervator - this doesn't belong in the math lib. It isn't a
math type or related functionality.

**Comment by msteiger** [comment]
Alright - closing in favor of https://github.com/Terasology/Pathfinding/pull/17

**Pull request closed without merging**
